spring.application.name=RideShare
server.port=8081
spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/rideshare}

jwt.secret=${JWT_SECRET:change-me-please-very-secret-key}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
